INSERT INTO logradouros (nome) VALUES ('Acampamento');
INSERT INTO logradouros (nome) VALUES ('Acesso');
INSERT INTO logradouros (nome) VALUES ('Adro');
INSERT INTO logradouros (nome) VALUES ('Aeroporto');
INSERT INTO logradouros (nome) VALUES ('Alameda');
INSERT INTO logradouros (nome) VALUES ('Alto');
INSERT INTO logradouros (nome) VALUES ('Área');
INSERT INTO logradouros (nome) VALUES ('Área Especial');
INSERT INTO logradouros (nome) VALUES ('Artéria');
INSERT INTO logradouros (nome) VALUES ('Atalho');
INSERT INTO logradouros (nome) VALUES ('Avenida');
INSERT INTO logradouros (nome) VALUES ('Avenida Contorno');
INSERT INTO logradouros (nome) VALUES ('Baixa');
INSERT INTO logradouros (nome) VALUES ('Balão');
INSERT INTO logradouros (nome) VALUES ('Balneário');
INSERT INTO logradouros (nome) VALUES ('Beco');
INSERT INTO logradouros (nome) VALUES ('Belvedere');
INSERT INTO logradouros (nome) VALUES ('Bloco');
INSERT INTO logradouros (nome) VALUES ('Bosque');
INSERT INTO logradouros (nome) VALUES ('Boulevard');
INSERT INTO logradouros (nome) VALUES ('Buraco');
INSERT INTO logradouros (nome) VALUES ('Cais');
INSERT INTO logradouros (nome) VALUES ('Calçada');
INSERT INTO logradouros (nome) VALUES ('Caminho');
INSERT INTO logradouros (nome) VALUES ('Campo');
INSERT INTO logradouros (nome) VALUES ('Canal');
INSERT INTO logradouros (nome) VALUES ('Chácara');
INSERT INTO logradouros (nome) VALUES ('Chapadão');
INSERT INTO logradouros (nome) VALUES ('Circular');
INSERT INTO logradouros (nome) VALUES ('Colônia');
INSERT INTO logradouros (nome) VALUES ('Complexo Viário');
INSERT INTO logradouros (nome) VALUES ('Condomínio');
INSERT INTO logradouros (nome) VALUES ('Conjunto');
INSERT INTO logradouros (nome) VALUES ('Crredor');
INSERT INTO logradouros (nome) VALUES ('Córrego');
INSERT INTO logradouros (nome) VALUES ('Descida');
INSERT INTO logradouros (nome) VALUES ('Desvio');
INSERT INTO logradouros (nome) VALUES ('Distrito');
INSERT INTO logradouros (nome) VALUES ('Elevada');
INSERT INTO logradouros (nome) VALUES ('Entrada Particular');
INSERT INTO logradouros (nome) VALUES ('Entre Quadra');
INSERT INTO logradouros (nome) VALUES ('Escada');
INSERT INTO logradouros (nome) VALUES ('Esplanada');
INSERT INTO logradouros (nome) VALUES ('Estação');
INSERT INTO logradouros (nome) VALUES ('Estacionamento');
INSERT INTO logradouros (nome) VALUES ('Estádio');
INSERT INTO logradouros (nome) VALUES ('Estância');
INSERT INTO logradouros (nome) VALUES ('Estrada');
INSERT INTO logradouros (nome) VALUES ('Estrada Municipal');
INSERT INTO logradouros (nome) VALUES ('Favela');
INSERT INTO logradouros (nome) VALUES ('Fazenda');
INSERT INTO logradouros (nome) VALUES ('Feira');
INSERT INTO logradouros (nome) VALUES ('Ferrovia');
INSERT INTO logradouros (nome) VALUES ('Fonte');
INSERT INTO logradouros (nome) VALUES ('Forte');
INSERT INTO logradouros (nome) VALUES ('Galeria');
INSERT INTO logradouros (nome) VALUES ('Granja');
INSERT INTO logradouros (nome) VALUES ('Habitacional');
INSERT INTO logradouros (nome) VALUES ('Ilha');
INSERT INTO logradouros (nome) VALUES ('Jardim');
INSERT INTO logradouros (nome) VALUES ('Jardinete');
INSERT INTO logradouros (nome) VALUES ('Ladeira');
INSERT INTO logradouros (nome) VALUES ('Lago');
INSERT INTO logradouros (nome) VALUES ('Lagoa');
INSERT INTO logradouros (nome) VALUES ('Largo');
INSERT INTO logradouros (nome) VALUES ('Loteamento');
INSERT INTO logradouros (nome) VALUES ('Marina');
INSERT INTO logradouros (nome) VALUES ('Módulo');
INSERT INTO logradouros (nome) VALUES ('Monte');
INSERT INTO logradouros (nome) VALUES ('Morro');
INSERT INTO logradouros (nome) VALUES ('Núcleo');
INSERT INTO logradouros (nome) VALUES ('Parada');
INSERT INTO logradouros (nome) VALUES ('Paradouro');
INSERT INTO logradouros (nome) VALUES ('Paralela');
INSERT INTO logradouros (nome) VALUES ('Parque');
INSERT INTO logradouros (nome) VALUES ('Passagem');
INSERT INTO logradouros (nome) VALUES ('Passagem Subterrânea');
INSERT INTO logradouros (nome) VALUES ('Passarela');
INSERT INTO logradouros (nome) VALUES ('Passeio');
INSERT INTO logradouros (nome) VALUES ('Pátio');
INSERT INTO logradouros (nome) VALUES ('Ponta');
INSERT INTO logradouros (nome) VALUES ('Porto');
INSERT INTO logradouros (nome) VALUES ('Praça');
INSERT INTO logradouros (nome) VALUES ('Praça de Esportes');
INSERT INTO logradouros (nome) VALUES ('Praia');
INSERT INTO logradouros (nome) VALUES ('Prolongamento');
INSERT INTO logradouros (nome) VALUES ('Quadra');
INSERT INTO logradouros (nome) VALUES ('Quinta');
INSERT INTO logradouros (nome) VALUES ('Ramal');
INSERT INTO logradouros (nome) VALUES ('Rampa');
INSERT INTO logradouros (nome) VALUES ('Rampa');
INSERT INTO logradouros (nome) VALUES ('Recanto');
INSERT INTO logradouros (nome) VALUES ('Residencial');
INSERT INTO logradouros (nome) VALUES ('Reta');
INSERT INTO logradouros (nome) VALUES ('Retiro');
INSERT INTO logradouros (nome) VALUES ('Retorno');
INSERT INTO logradouros (nome) VALUES ('Rodovia');
INSERT INTO logradouros (nome) VALUES ('Rotatória');
INSERT INTO logradouros (nome) VALUES ('Rotula');
INSERT INTO logradouros (nome) VALUES ('Rua');
INSERT INTO logradouros (nome) VALUES ('Rua de Ligação');
INSERT INTO logradouros (nome) VALUES ('Rua de Pedestre');
INSERT INTO logradouros (nome) VALUES ('Servidão');
INSERT INTO logradouros (nome) VALUES ('Setor');
INSERT INTO logradouros (nome) VALUES ('Sitio');
INSERT INTO logradouros (nome) VALUES ('Subida');
INSERT INTO logradouros (nome) VALUES ('Terminal');
INSERT INTO logradouros (nome) VALUES ('Travessa');
INSERT INTO logradouros (nome) VALUES ('Travessa particular');
INSERT INTO logradouros (nome) VALUES ('Trecho');
INSERT INTO logradouros (nome) VALUES ('Trevo');
INSERT INTO logradouros (nome) VALUES ('Trincheira');
INSERT INTO logradouros (nome) VALUES ('Túnel');
INSERT INTO logradouros (nome) VALUES ('Unidade');
INSERT INTO logradouros (nome) VALUES ('Vala');
INSERT INTO logradouros (nome) VALUES ('Vale');
INSERT INTO logradouros (nome) VALUES ('Variante');
INSERT INTO logradouros (nome) VALUES ('Vereda');
INSERT INTO logradouros (nome) VALUES ('Via');
INSERT INTO logradouros (nome) VALUES ('Via de acesso');
INSERT INTO logradouros (nome) VALUES ('Via de pedestre');
INSERT INTO logradouros (nome) VALUES ('Via elevado');
INSERT INTO logradouros (nome) VALUES ('Via expressa');
INSERT INTO logradouros (nome) VALUES ('Viaduto');
INSERT INTO logradouros (nome) VALUES ('Viela');
INSERT INTO logradouros (nome) VALUES ('Vila');
INSERT INTO logradouros (nome) VALUES ('Zigue-Zague');
