INSERT INTO planos_saudes (nome_plano) VALUES ('Agemed');
INSERT INTO planos_saudes (nome_plano) VALUES ('Allianz Saúde');
INSERT INTO planos_saudes (nome_plano) VALUES ('Amil');
INSERT INTO planos_saudes (nome_plano) VALUES ('Blue Med Saúde');
INSERT INTO planos_saudes (nome_plano) VALUES ('Bradesco Saúde');
INSERT INTO planos_saudes (nome_plano) VALUES ('Caixa Seguros Saúde');
INSERT INTO planos_saudes (nome_plano) VALUES ('Cassi');
INSERT INTO planos_saudes (nome_plano) VALUES ('Fundação Saúde Itaú');
INSERT INTO planos_saudes (nome_plano) VALUES ('Geap');
INSERT INTO planos_saudes (nome_plano) VALUES ('Golden Cross');
INSERT INTO planos_saudes (nome_plano) VALUES ('Green Line');
INSERT INTO planos_saudes (nome_plano) VALUES ('Lincx Saúde');
INSERT INTO planos_saudes (nome_plano) VALUES ('Mediservice');
INSERT INTO planos_saudes (nome_plano) VALUES ('Next Saúde');
INSERT INTO planos_saudes (nome_plano) VALUES ('Notre Dame Intermédica');
INSERT INTO planos_saudes (nome_plano) VALUES ('Omint');
INSERT INTO planos_saudes (nome_plano) VALUES ('One Health');
INSERT INTO planos_saudes (nome_plano) VALUES ('Porto Seguro Saúde');
INSERT INTO planos_saudes (nome_plano) VALUES ('Promed');
INSERT INTO planos_saudes (nome_plano) VALUES ('Qualicorp');
INSERT INTO planos_saudes (nome_plano) VALUES ('Saúde Beneficência');
INSERT INTO planos_saudes (nome_plano) VALUES ('Smile Saúde');
INSERT INTO planos_saudes (nome_plano) VALUES ('Sul América');
INSERT INTO planos_saudes (nome_plano) VALUES ('Trasmontano Saúde');
INSERT INTO planos_saudes (nome_plano) VALUES ('Unimed');