INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('ABBOTT','Abbott Laboratórios do Brasil Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('ABBOTT SAÚDE','Abbott Prods. para Saúde Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('ABBVIE','Abbvie Farmacêutica Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('ABL','Antibióticos do Brasil Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('ACCORD','Accord Farmacêutica Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('ACHÉ','Aché Laboratórios Farmacêuticos S.A.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('ACTAVIS','Actavis Farmacêutica Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('ALCON','Alcon Lab. do Brasil Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('ALLERGAN','Allergan Produtos Farmacêuticos Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('ALTHAIA','Althaia Indústria Farmacêutica');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('AMGEN','Amgen Biotecnologia do Brasil Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('APSEN','Apsen Farmacêutica S.A.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('ARESE','Ativus - Divisão Arese Pharma');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('ARISTON','Ariston Ind. Químicas e Farmacêuticas Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('ASPEN PHARMA','Aspen Pharma Indústria Farmacêutica Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('ASTELLAS','Astellas Farma Brasil Imp. e Distr. de Med. Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('ASTRAZENECA','AstraZeneca do Brasil Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('ATIVUS','Ativus Farmacêutica Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('AUROBINDO','Aurobindo Pharma Indústria Farmacêutica Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('AUROBINDOPHARMA','Aurobindo Pharma Produtos Farmacêuticos Ltda');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('AVERT','Avert Laboratórios Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('B-MS','Bristol-Myers Squibb Farmacêutica S/A.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('BAGÓ','Laboratórios Bagó Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('BALDACCI','Lab. Baldacci S.A.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('BARRENNE','Barrenne Ind. Farmacêutica Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('BAUSCH & LOMB','BL Indústria Ótica Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('BAXTER','Baxter Hospitalar Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('BAYER','Bayer S.A.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('BEKER','Beker Produtos Fármacos Hospitalares');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('BERGAMO','Lab. Químico Farmacêutico Bergamo Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('BESINS','Besins Healthcare Brasil Comercial e Distribuidora');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('BIOCHIMICO','Instituto Biochimico Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('BIOLAB SANUS','Biolab Sanus Farmacêutica Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('BIOSINTÉTICA','Biosintética Farmacêutica Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('BLAU','Blau Farmacêutica S/A.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('BOEHRINGER','Boehringer Ingelheim do Brasil');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('BRAINFARMA','Brainfarma Ind. Quím. e Farmacêutica Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('BRASTERÁPICA','Brasterápica Ind. Farmacêutica Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('BUNKER','Bunker Ind. Farmacêutica Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('CATARINENSE','Lab. Catarinense S.A.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('CAZI','Cazi Química Farmacêutica Ind. e Com. Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('CELLTRION','Celltrion Healthcare Dist. Prod. Farm. Brasil Ltda');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('CHIESI','Chiesi Farmacêutica Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('CIFARMA','Cifarma Científica Farmacêutica Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('CIMED','Cimed Indústria de Medicamentos Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('CITOPHARMA','Casula & Vasconselos Ind. Farm. e Com. Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('CLARIS','Claris Produtos Farmacêuticos do Brasil Ltda');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('COSMED','Cosmed Indústria de Cosméticos e Medicamentos S.A.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('CRISTÁLIA','Cristália Produtos Químicos Farmacêuticos Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('CSL BEHRING','CSL Behring Com. de Prods. Farmacêuticos Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('DAIICHI SANKYO','Daiichi Sankyo Brasil Farmacêutica Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('DAUDT','Lab. Daudt Oliveira Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('DELTA','Instituto Terapêutico Delta Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('DIFFUCAP-CHEMO.','Diffucap-Chemobras Química e Farmacêutica Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('DOVALLE','Farmoterápica Dovalle Ind. Quim. e Farm. Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('DR. REDDYS','Dr. Reddys Farmacêutica do Brasil Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('DROXTER','Droxter Indústria, Comércio e Participações Ltda');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('EISAI','Eisai Laboratórios Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('ELI LILLY','Eli Lilly do Brasil Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('ELOFAR','Lab. Farmacêutico Elofar Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('EMS','EMS Ind. Farmacêutica Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('EMS OTC','EMS Ind. Farmacêutica Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('EUROFARMA','Eurofarma Laboratórios Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('EXELTIS','Exeltis Laboratório Farmacêutico Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('FARMABR B.ATAL.','Farmabraz Beta Atalaia Farmacêutica Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('FERRING','Laboratórios Ferring Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('FQM','Farmoquímica S.A.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('GALDERMA','Galderma Brasil Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('GALLIA','Gallia Farmacêutica Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('GENÉRIC.GERMED','Divisão da EMS Ind. Farmacêutica Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('GENÉRIC.LEGRAND','Divisão da Nature Plus Farm. Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('GENZYME','Genzyme do Brasil Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('GEOLAB','Geolab Indústria Farmacêutica Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('GERMED PHARMA','Germed Farmacêutica Ltda');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('GEYER','Geyer Medicamentos S.A.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('GLAXOSMITHKLINE','GlaxoSmithKline Brasil Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('GLENMARK','Glenmark Farmacêutica Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('GLOBO','Laboratório Globo Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('GROSS','Lab. Gross S.A.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('GRUNENTHAL','Grunenthal Farmacêutica do Brasil Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('H.B. FARMA','H. B. Farma Laboratórios Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('HALLER','Química Haller Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('HEBRON','Infan Ind. Quím. Farm. Nacional S/A');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('HEEL DO BRASIL','Heel do Brasil Biomédica');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('HERBARIUM','Herbarium Laboratório Botânico Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('HERTZ','Kley Hertz S.A.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('HISAMITSU','Hisamitsu Farmacêutica do Brasil Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('HOSPIRA','Hospira Produtos Hospitalares Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('HYPM','Hypermarcas S/A');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('IGEFARMA','Igefarma Laboratórios S.A.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('J & J','Johnson & Johnson Comércio e Distribuição Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('JANSSEN-CILAG','Janssen-Cilag Farmacêutica Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('LATINOFARMA','Latinofarma Industrias Farmacêuticas Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('LEGRAND','Divisão da EMS Ind. Farmacêutica Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('LEGRAND/OTC','Divisão da EMS Ind. Farmacêutica Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('LEGRAND/PRESC','Divisão da EMS Ind. Farmacêutica Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('LEGRAND/TARJA','Divisão da EMS Ind. Farmacêutica Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('LEO PHARMA','LEO Pharma Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('LEOFARMA','Leofarma Com. e Ind. Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('LIBBS','Libbs Farmacêutica Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('LUNDBECK','Lundbeck Brasil Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('MABRA','Mabra Farmacêutica Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('MANTECORP FSA','Mantecorp Indústria Química e Farmacêutica Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('MARJAN FARMA','Marjan Indústria e Comércio Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('MEAD JOHNSON','Mead Johnson');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('MEDA PHARMA','Meda Pharma Imp. e Exp de Prod. Farm. Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('MEDLEY','Medley S.A. Indústria Farmacêutica.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('MEDQUÍMICA','Medquímica Indústria Farmacêutica Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('MELCON','Ind. Farmacêutica Melcon do Brasil LTDA');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('MERCK','Merck S.A. Ind. Químicas');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('MERCK SHARP','Merck Sharp & Dohme Farmacêutica Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('MOMENTA','Momenta Farmacêutica Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('MULTILAB','Multilab Ind. e Com. Prods. Farmacêuticos Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('MYRALIS PHARMA','Myralis Pharma Ltda. EPP');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('NEO QUÍMICA','Lab. Neo Química Com. e Ind. Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('NESTLÉ','Nestlé Ind. e Com. Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('NIKKHO','Química e Farmacêutica Nikkho do Brasil Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('NOVA QUÍMICA','Nova Química Farmacêutica Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('NOVARTIS','Novartis Biociências S.A.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('NOVO NORDISK','Novo Nordisk Farmacêutica do Brasil Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('O.MORAES','Lab. Osório de Moraes Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('OCTAPHARMA','Octapharma Brasil Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('ONE FARMA','One Farma Ind. Farmacêutica LTDA');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('OPHTHALMOS','Ophthalmos Ind. e Com. de Prods. Farm. Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('PFIZER','Lab. Pfizer Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('PRATI,DONADUZZI','Prati, Donaduzzi & Cia. Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('PROCTER GAMBLE','Procter & Gamble do Brasil S.A.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('PROFITUS','Laboratório Profitus Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('R. BENCKISER','Reckitt Benckiser (Brasil) Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('RANBAXY','Ranbaxy Farmacêutica Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('RÉGIUS','Laboratório Régius Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('ROCHE','Prod. Roche Químicos e Farmacêuticos S.A.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('SANDOZ','Sandoz do Brasil Indústria Farmacêutica Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('SANOFI PASTEUR','Sanofi Pasteur Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('SANOFI-AVENTIS','Sanofi-Aventis Farmacêutica Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('SANOFI/SYNTHEL','Sanofi-Aventis Farmacêutica Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('SANTISA','Santisa Laboratório Farmacêutico S/A.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('SANVAL','Sanval Indústria e Comércio Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('SCHERING','Schering do Brasil Química e Farm. Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('SCHERING PLOUGH','Schering Plough Produtos Farmacêuticos Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('SERONO','Serono Produtos Farmacêuticos Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('SERVIER','Laboratórios Servier do Brasil Ltda.');
INSERT INTO fabricantes (sigla, nome_fabricante) VALUES ('SHIRE','Shire Farmacêutica Brasil Ltda');
