INSERT INTO orgaos_expedidores (nome) VALUES ('COMAER - Comando da Aeronáutica');
INSERT INTO orgaos_expedidores (nome) VALUES ('EB - Exército Brasileiro');
INSERT INTO orgaos_expedidores (nome) VALUES ('MB - Marinha do Brasil');
INSERT INTO orgaos_expedidores (nome) VALUES ('PF - Polícia Federal');
INSERT INTO orgaos_expedidores (nome) VALUES ('CRA - Conselho Regional de Administração');
INSERT INTO orgaos_expedidores (nome) VALUES ('CRAA - Conselho Regional de Assistência Social');
INSERT INTO orgaos_expedidores (nome) VALUES ('CRB - Conselho Regional de Biblioteconomia');
INSERT INTO orgaos_expedidores (nome) VALUES ('CRC - Conselho Regional de Contabilidade');
INSERT INTO orgaos_expedidores (nome) VALUES ('CRCI - Conselho Regional de Corretores Imóveis');
INSERT INTO orgaos_expedidores (nome) VALUES ('CREN - Conselho Regional de Enfermagem');
INSERT INTO orgaos_expedidores (nome) VALUES ('CREA - Conselho Regional de Engenharia, Arquitetura e Agronomia');
INSERT INTO orgaos_expedidores (nome) VALUES ('CRE - Conselho Regional de Estatística');
INSERT INTO orgaos_expedidores (nome) VALUES ('CRF - Conselho Regional de Farmácia');
INSERT INTO orgaos_expedidores (nome) VALUES ('CRFTO - Conselho Regional de Fisioterapia e Terapia Ocupacional');
INSERT INTO orgaos_expedidores (nome) VALUES ('CRM - Conselho Regional de Medicina');
INSERT INTO orgaos_expedidores (nome) VALUES ('CRMV - Conselho Regional de Medicina Veterinária');
INSERT INTO orgaos_expedidores (nome) VALUES ('OMB - Ordem dos Músicos do Brasil');
INSERT INTO orgaos_expedidores (nome) VALUES ('CRN - Conselho Regional de Nutrição');
INSERT INTO orgaos_expedidores (nome) VALUES ('CRO - Conselho Regional de Odontologia');
INSERT INTO orgaos_expedidores (nome) VALUES ('CRPRP - Conselho Regional de Profissionais de Relações Públicas');
INSERT INTO orgaos_expedidores (nome) VALUES ('CRP - Conselho Regional de Psicologia');
INSERT INTO orgaos_expedidores (nome) VALUES ('CRQ - Conselho Regional de Química');
INSERT INTO orgaos_expedidores (nome) VALUES ('CRRC - Conselho Regional de Representantes Comerciais');
INSERT INTO orgaos_expedidores (nome) VALUES ('OAB - Ordemdos Advogados do Brasil');
INSERT INTO orgaos_expedidores (nome) VALUES ('OE - Outros Emissores');
INSERT INTO orgaos_expedidores (nome) VALUES ('DE - Documento Estrangeiro');
INSERT INTO orgaos_expedidores (nome) VALUES ('SSP - Secretaria de Segurança Pública');
INSERT INTO orgaos_expedidores (nome) VALUES ('PM - Polícia Militar');
INSERT INTO orgaos_expedidores (nome) VALUES ('PC - Policia Civil');
INSERT INTO orgaos_expedidores (nome) VALUES ('CNT - Carteira Nacional de Habilitação');
INSERT INTO orgaos_expedidores (nome) VALUES ('DIC - Diretoria de Identificação Civil');
INSERT INTO orgaos_expedidores (nome) VALUES ('CTPS - Carteira de Trabaho e Previdência Social');
INSERT INTO orgaos_expedidores (nome) VALUES ('FGTS - Fundo de Garantia do Tempo de Serviço');
INSERT INTO orgaos_expedidores (nome) VALUES ('IFP - Instituto Félix Pacheco');
INSERT INTO orgaos_expedidores (nome) VALUES ('IPF - Instituto Pereira Faustino');
INSERT INTO orgaos_expedidores (nome) VALUES ('IML - Instituto Médico-Legal');
INSERT INTO orgaos_expedidores (nome) VALUES ('MTE - Ministério do Trabalho e Emprego');
INSERT INTO orgaos_expedidores (nome) VALUES ('SES - Carteira de Estrangeiro');
INSERT INTO orgaos_expedidores (nome) VALUES ('SJS - Secretaria da Justiça e Segurança');
INSERT INTO orgaos_expedidores (nome) VALUES ('SJTS - Secretaria da Justiça do Trabalho e Segurança');
INSERT INTO orgaos_expedidores (nome) VALUES ('ZZZ - Outros (inclusive exterior)');
